import { Token } from './types';

const allTokensForSimilarity: Omit<Token, 'tags' | 'stats' | 'isNew' | 'isFinalStretch' | 'isMigrated' | 'similarTokens'>[] = [
    {
      id: 'nectar-similar-1',
      name: 'core',
      subtitle: 'NectarFi-SOL',
      imageUrl: 'https://picsum.photos/seed/401/100/100',
      creatorAddress: '5xgH...Jiej',
      age: '5mo',
      marketCap: 1520000,
      volume: 1500,
      fValue: 0.04,
      txCount: 7000000,
      solAmount: 1.5,
    },
     {
      id: 'nectar-similar-2',
      name: 'SCORE',
      subtitle: 'Honey-SOL',
      imageUrl: 'https://picsum.photos/seed/402/100/100',
      creatorAddress: 'abcdef...ghij',
      age: '1y',
      marketCap: 15000,
      volume: 1000,
      fValue: 0.03,
      txCount: 1500,
      solAmount: 1.1,
    },
    {
      id: 'similar-3',
      name: 'PEPE',
      subtitle: 'froggy style',
      imageUrl: 'https://picsum.photos/seed/3/100/100',
      creatorAddress: 'Cef3...yPUi',
      age: '1m',
      marketCap: 89000,
      volume: 4200,
      fValue: 0.021,
      txCount: 18,
      solAmount: 0.5,
    },
    {
      id: 'similar-4',
      name: 'BONK',
      subtitle: 'the OG bonk',
      imageUrl: 'https://picsum.photos/seed/4/100/100',
      creatorAddress: 'Dkl4...zQWs',
      age: '5m',
      marketCap: 540000,
      volume: 25000,
      fValue: 0.12,
      txCount: 102,
      solAmount: 3.4,
    },
    {
      id: 'similar-5',
      name: 'WIF',
      subtitle: 'dog wif hat',
      imageUrl: 'https://picsum.photos/seed/5/100/100',
      creatorAddress: 'Emn5...aRTy',
      age: '30m',
      marketCap: 1200000,
      volume: 80000,
      fValue: 0.25,
      txCount: 250,
      solAmount: 10.1,
    },
];


const tokens: Omit<Token, 'similarTokens'>[] = [
  // New Pairs
  {
    id: 'leo-1',
    name: 'Pointing',
    subtitle: 'Leonardo DiCaprio Pointing',
    imageUrl: 'https://picsum.photos/seed/1/100/100',
    creatorAddress: '6j2z...pump',
    age: '2s',
    marketCap: 4940,
    volume: 757,
    fValue: 0.024,
    txCount: 18,
    stats: { users: 13, candlesticks: 3, trophies: 0, crowns: '0/73' },
    tags: [
      { icon: 'user', value: 15, unit: '%', color: 'green' },
      { icon: 'chef', value: 7, unit: '%', color: 'green', duration: '2d' },
      { icon: 'target', value: 15, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 15, unit: '%', color: 'red' },
    ],
    solAmount: 0,
    isNew: true,
  },
  {
    id: 'shib-1',
    name: 'SHIB',
    subtitle: 'another dog coin',
    imageUrl: 'https://picsum.photos/seed/2/100/100',
    creatorAddress: 'Bdj2...xLTr',
    age: '42s',
    marketCap: 250000,
    volume: 12000,
    fValue: 0.05,
    txCount: 55,
    stats: { users: 32, candlesticks: 2, trophies: 1, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 88, unit: '%', color: 'red' },
      { icon: 'chef', value: 10, unit: '%', color: 'green', duration: '5m' },
      { icon: 'target', value: 92, unit: '%', color: 'red' },
      { icon: 'ghost', value: 5, unit: '%', color: 'green' },
      { icon: 'cubes', value: 2, unit: '%', color: 'green' },
    ],
    solAmount: 1.2,
    isNew: true,
  },
  {
    id: 'new-3',
    name: 'GigaChad',
    subtitle: 'Absolute Unit',
    imageUrl: 'https://picsum.photos/seed/103/100/100',
    creatorAddress: 'CHAD...pump',
    age: '1s',
    marketCap: 12000,
    volume: 1500,
    fValue: 0.08,
    txCount: 25,
    stats: { users: 20, candlesticks: 5, trophies: 0, crowns: '0/100' },
    tags: [
      { icon: 'user', value: 20, unit: '%', color: 'green' },
      { icon: 'chef', value: 5, unit: '%', color: 'green', duration: '1d' },
      { icon: 'target', value: 10, unit: '%', color: 'red' },
      { icon: 'ghost', value: 1, unit: '%', color: 'green' },
      { icon: 'cubes', value: 12, unit: '%', color: 'red' },
    ],
    solAmount: 0.2,
    isNew: true,
  },
  {
    id: 'new-4',
    name: 'Stonk',
    subtitle: 'To the Moon',
    imageUrl: 'https://picsum.photos/seed/104/100/100',
    creatorAddress: 'STON...pump',
    age: '5s',
    marketCap: 8000,
    volume: 1100,
    fValue: 0.03,
    txCount: 15,
    stats: { users: 10, candlesticks: 2, trophies: 0, crowns: '0/50' },
    tags: [
      { icon: 'user', value: 10, unit: '%', color: 'green' },
      { icon: 'chef', value: 8, unit: '%', color: 'green', duration: '3h' },
      { icon: 'target', value: 25, unit: '%', color: 'red' },
      { icon: 'ghost', value: 2, unit: '%', color: 'green' },
      { icon: 'cubes', value: 5, unit: '%', color: 'green' },
    ],
    solAmount: 0.1,
    isNew: true,
  },
  {
    id: 'new-5',
    name: 'Diamond Hands',
    subtitle: 'HODL',
    imageUrl: 'https://picsum.photos/seed/105/100/100',
    creatorAddress: 'HODL...pump',
    age: '12s',
    marketCap: 22000,
    volume: 3000,
    fValue: 0.06,
    txCount: 30,
    stats: { users: 25, candlesticks: 8, trophies: 1, crowns: '1/80' },
    tags: [
      { icon: 'user', value: 30, unit: '%', color: 'green' },
      { icon: 'chef', value: 15, unit: '%', color: 'green', duration: '12h' },
      { icon: 'target', value: 20, unit: '%', color: 'red' },
      { icon: 'ghost', value: 3, unit: '%', color: 'green' },
      { icon: 'cubes', value: 18, unit: '%', color: 'red' },
    ],
    solAmount: 0.4,
    isNew: true,
  },
  {
    id: 'new-6',
    name: 'Laser Eyes',
    subtitle: 'Visionary',
    imageUrl: 'https://picsum.photos/seed/106/100/100',
    creatorAddress: 'EYES...pump',
    age: '15s',
    marketCap: 15000,
    volume: 2000,
    fValue: 0.04,
    txCount: 22,
    stats: { users: 18, candlesticks: 4, trophies: 0, crowns: '0/60' },
    tags: [
      { icon: 'user', value: 18, unit: '%', color: 'green' },
      { icon: 'chef', value: 10, unit: '%', color: 'green', duration: '6h' },
      { icon: 'target', value: 15, unit: '%', color: 'red' },
      { icon: 'ghost', value: 2, unit: '%', color: 'green' },
      { icon: 'cubes', value: 10, unit: '%', color: 'red' },
    ],
    solAmount: 0.3,
    isNew: true,
  },
  {
    id: 'new-7',
    name: 'CatJAM',
    subtitle: 'Vibing Cat',
    imageUrl: 'https://picsum.photos/seed/107/100/100',
    creatorAddress: 'JAM...pump',
    age: '18s',
    marketCap: 9500,
    volume: 1300,
    fValue: 0.02,
    txCount: 19,
    stats: { users: 12, candlesticks: 3, trophies: 0, crowns: '0/40' },
    tags: [
      { icon: 'user', value: 12, unit: '%', color: 'green' },
      { icon: 'chef', value: 6, unit: '%', color: 'green', duration: '2h' },
      { icon: 'target', value: 22, unit: '%', color: 'red' },
      { icon: 'ghost', value: 1, unit: '%', color: 'green' },
      { icon: 'cubes', value: 8, unit: '%', color: 'green' },
    ],
    solAmount: 0.15,
    isNew: true,
  },
  {
    id: 'new-8',
    name: 'Sadge',
    subtitle: 'Feels Bad Man',
    imageUrl: 'https://picsum.photos/seed/108/100/100',
    creatorAddress: 'SAD...pump',
    age: '21s',
    marketCap: 3000,
    volume: 400,
    fValue: 0.01,
    txCount: 10,
    stats: { users: 8, candlesticks: 1, trophies: 0, crowns: '0/20' },
    tags: [
      { icon: 'user', value: 5, unit: '%', color: 'green' },
      { icon: 'chef', value: 2, unit: '%', color: 'green', duration: '1h' },
      { icon: 'target', value: 50, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 2, unit: '%', color: 'red' },
    ],
    solAmount: 0.05,
    isNew: true,
  },
  {
    id: 'new-9',
    name: 'Monke',
    subtitle: 'Return to Monke',
    imageUrl: 'https://picsum.photos/seed/109/100/100',
    creatorAddress: 'MONK...pump',
    age: '25s',
    marketCap: 18000,
    volume: 2500,
    fValue: 0.05,
    txCount: 28,
    stats: { users: 22, candlesticks: 6, trophies: 0, crowns: '0/70' },
    tags: [
      { icon: 'user', value: 25, unit: '%', color: 'green' },
      { icon: 'chef', value: 12, unit: '%', color: 'green', duration: '8h' },
      { icon: 'target', value: 18, unit: '%', color: 'red' },
      { icon: 'ghost', value: 4, unit: '%', color: 'green' },
      { icon: 'cubes', value: 15, unit: '%', color: 'red' },
    ],
    solAmount: 0.35,
    isNew: true,
  },
  {
    id: 'new-10',
    name: 'Ape',
    subtitle: 'Apes Together Strong',
    imageUrl: 'https://picsum.photos/seed/110/100/100',
    creatorAddress: 'APE...pump',
    age: '28s',
    marketCap: 30000,
    volume: 4000,
    fValue: 0.07,
    txCount: 35,
    stats: { users: 30, candlesticks: 10, trophies: 1, crowns: '1/90' },
    tags: [
      { icon: 'user', value: 35, unit: '%', color: 'green' },
      { icon: 'chef', value: 18, unit: '%', color: 'green', duration: '15h' },
      { icon: 'target', value: 25, unit: '%', color: 'red' },
      { icon: 'ghost', value: 5, unit: '%', color: 'green' },
      { icon: 'cubes', value: 20, unit: '%', color: 'red' },
    ],
    solAmount: 0.5,
    isNew: true,
  },
  {
    id: 'new-11',
    name: 'Poggers',
    subtitle: 'Play of the Game',
    imageUrl: 'https://picsum.photos/seed/111/100/100',
    creatorAddress: 'POG...pump',
    age: '30s',
    marketCap: 11000,
    volume: 1600,
    fValue: 0.035,
    txCount: 20,
    stats: { users: 15, candlesticks: 4, trophies: 0, crowns: '0/55' },
    tags: [
      { icon: 'user', value: 15, unit: '%', color: 'green' },
      { icon: 'chef', value: 8, unit: '%', color: 'green', duration: '4h' },
      { icon: 'target', value: 30, unit: '%', color: 'red' },
      { icon: 'ghost', value: 2, unit: '%', color: 'green' },
      { icon: 'cubes', value: 10, unit: '%', color: 'green' },
    ],
    solAmount: 0.2,
    isNew: true,
  },
  {
    id: 'new-12',
    name: 'KEKW',
    subtitle: 'Contagious Laughter',
    imageUrl: 'https://picsum.photos/seed/112/100/100',
    creatorAddress: 'KEKW...pump',
    age: '32s',
    marketCap: 7500,
    volume: 900,
    fValue: 0.025,
    txCount: 14,
    stats: { users: 11, candlesticks: 2, trophies: 0, crowns: '0/30' },
    tags: [
      { icon: 'user', value: 10, unit: '%', color: 'green' },
      { icon: 'chef', value: 5, unit: '%', color: 'green', duration: '2.5h' },
      { icon: 'target', value: 40, unit: '%', color: 'red' },
      { icon: 'ghost', value: 1, unit: '%', color: 'green' },
      { icon: 'cubes', value: 5, unit: '%', color: 'red' },
    ],
    solAmount: 0.1,
    isNew: true,
  },
  {
    id: 'new-13',
    name: 'PepeLaugh',
    subtitle: 'He Doesn\'t Know',
    imageUrl: 'https://picsum.photos/seed/113/100/100',
    creatorAddress: 'LAUGH...pump',
    age: '35s',
    marketCap: 6000,
    volume: 800,
    fValue: 0.02,
    txCount: 12,
    stats: { users: 9, candlesticks: 2, trophies: 0, crowns: '0/25' },
    tags: [
      { icon: 'user', value: 8, unit: '%', color: 'green' },
      { icon: 'chef', value: 4, unit: '%', color: 'green', duration: '1.5h' },
      { icon: 'target', value: 35, unit: '%', color: 'red' },
      { icon: 'ghost', value: 1, unit: '%', color: 'green' },
      { icon: 'cubes', value: 4, unit: '%', color: 'red' },
    ],
    solAmount: 0.08,
    isNew: true,
  },
  {
    id: 'new-14',
    name: 'Copium',
    subtitle: 'Inhale',
    imageUrl: 'https://picsum.photos/seed/114/100/100',
    creatorAddress: 'COPE...pump',
    age: '38s',
    marketCap: 4500,
    volume: 600,
    fValue: 0.015,
    txCount: 11,
    stats: { users: 7, candlesticks: 1, trophies: 0, crowns: '0/15' },
    tags: [
      { icon: 'user', value: 6, unit: '%', color: 'green' },
      { icon: 'chef', value: 3, unit: '%', color: 'green', duration: '1h' },
      { icon: 'target', value: 55, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 3, unit: '%', color: 'red' },
    ],
    solAmount: 0.06,
    isNew: true,
  },
  {
    id: 'new-15',
    name: 'Wojak',
    subtitle: 'That Feel',
    imageUrl: 'https://picsum.photos/seed/115/100/100',
    creatorAddress: 'FEEL...pump',
    age: '40s',
    marketCap: 2500,
    volume: 300,
    fValue: 0.01,
    txCount: 8,
    stats: { users: 5, candlesticks: 1, trophies: 0, crowns: '0/10' },
    tags: [
      { icon: 'user', value: 4, unit: '%', color: 'green' },
      { icon: 'chef', value: 2, unit: '%', color: 'green', duration: '30m' },
      { icon: 'target', value: 60, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 1, unit: '%', color: 'red' },
    ],
    solAmount: 0.04,
    isNew: true,
  },
  {
    id: 'new-16',
    name: 'NPC',
    subtitle: 'Gray Man',
    imageUrl: 'https://picsum.photos/seed/116/100/100',
    creatorAddress: 'NPC...pump',
    age: '42s',
    marketCap: 1500,
    volume: 200,
    fValue: 0.005,
    txCount: 5,
    stats: { users: 3, candlesticks: 0, trophies: 0, crowns: '0/5' },
    tags: [
      { icon: 'user', value: 2, unit: '%', color: 'green' },
      { icon: 'chef', value: 1, unit: '%', color: 'green', duration: '10m' },
      { icon: 'target', value: 70, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 0, unit: '%', color: 'red' },
    ],
    solAmount: 0.02,
    isNew: true,
  },
  {
    id: 'new-17',
    name: 'Swole Doge',
    subtitle: 'Much Strength',
    imageUrl: 'https://picsum.photos/seed/117/100/100',
    creatorAddress: 'SWOLE...pump',
    age: '45s',
    marketCap: 35000,
    volume: 5000,
    fValue: 0.08,
    txCount: 40,
    stats: { users: 35, candlesticks: 12, trophies: 1, crowns: '1/95' },
    tags: [
      { icon: 'user', value: 40, unit: '%', color: 'green' },
      { icon: 'chef', value: 20, unit: '%', color: 'green', duration: '20h' },
      { icon: 'target', value: 22, unit: '%', color: 'red' },
      { icon: 'ghost', value: 6, unit: '%', color: 'green' },
      { icon: 'cubes', value: 25, unit: '%', color: 'red' },
    ],
    solAmount: 0.6,
    isNew: true,
  },
  {
    id: 'new-18',
    name: 'Cheems',
    subtitle: 'Bonk',
    imageUrl: 'https://picsum.photos/seed/118/100/100',
    creatorAddress: 'CHEEM...pump',
    age: '48s',
    marketCap: 20000,
    volume: 2800,
    fValue: 0.055,
    txCount: 32,
    stats: { users: 28, candlesticks: 7, trophies: 0, crowns: '0/75' },
    tags: [
      { icon: 'user', value: 30, unit: '%', color: 'green' },
      { icon: 'chef', value: 14, unit: '%', color: 'green', duration: '10h' },
      { icon: 'target', value: 28, unit: '%', color: 'red' },
      { icon: 'ghost', value: 4, unit: '%', color: 'green' },
      { icon: 'cubes', value: 18, unit: '%', color: 'red' },
    ],
    solAmount: 0.45,
    isNew: true,
  },
  {
    id: 'new-19',
    name: 'Doge',
    subtitle: 'Much Wow',
    imageUrl: 'https://picsum.photos/seed/119/100/100',
    creatorAddress: 'DOGE...pump',
    age: '50s',
    marketCap: 40000,
    volume: 6000,
    fValue: 0.09,
    txCount: 45,
    stats: { users: 40, candlesticks: 15, trophies: 2, crowns: '2/100' },
    tags: [
      { icon: 'user', value: 45, unit: '%', color: 'green' },
      { icon: 'chef', value: 22, unit: '%', color: 'green', duration: '24h' },
      { icon: 'target', value: 20, unit: '%', color: 'red' },
      { icon: 'ghost', value: 8, unit: '%', color: 'green' },
      { icon: 'cubes', value: 30, unit: '%', color: 'red' },
    ],
    solAmount: 0.7,
    isNew: true,
  },
  {
    id: 'new-20',
    name: 'Galaxy Brain',
    subtitle: '5D Chess',
    imageUrl: 'https://picsum.photos/seed/120/100/100',
    creatorAddress: 'BRAIN...pump',
    age: '52s',
    marketCap: 50000,
    volume: 7500,
    fValue: 0.1,
    txCount: 50,
    stats: { users: 45, candlesticks: 18, trophies: 3, crowns: '3/110' },
    tags: [
      { icon: 'user', value: 50, unit: '%', color: 'green' },
      { icon: 'chef', value: 25, unit: '%', color: 'green', duration: '2d' },
      { icon: 'target', value: 15, unit: '%', color: 'red' },
      { icon: 'ghost', value: 10, unit: '%', color: 'green' },
      { icon: 'cubes', value: 35, unit: '%', color: 'red' },
    ],
    solAmount: 0.8,
    isNew: true,
  },

  // Final Stretch
  {
    id: 'pepe-1',
    name: 'PEPE',
    subtitle: 'froggy style',
    imageUrl: 'https://picsum.photos/seed/3/100/100',
    creatorAddress: 'Cef3...yPUi',
    age: '1m',
    marketCap: 89000,
    volume: 4200,
    fValue: 0.021,
    txCount: 18,
    stats: { users: 10, candlesticks: 1, trophies: 0, crowns: '0/1' },
    tags: [
      { icon: 'user', value: 99, unit: '%', color: 'red' },
      { icon: 'chef', value: 1, unit: '%', color: 'green', duration: '2m' },
      { icon: 'target', value: 95, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 1, unit: '%', color: 'green' },
    ],
    solAmount: 0.5,
    isFinalStretch: true,
  },
  {
    id: 'bonk-1',
    name: 'BONK',
    subtitle: 'the OG bonk',
    imageUrl: 'https://picsum.photos/seed/4/100/100',
    creatorAddress: 'Dkl4...zQWs',
    age: '5m',
    marketCap: 540000,
    volume: 25000,
    fValue: 0.12,
    txCount: 102,
    stats: { users: 150, candlesticks: 5, trophies: 3, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 75, unit: '%', color: 'red' },
      { icon: 'chef', value: 25, unit: '%', color: 'green', duration: '10m' },
      { icon: 'target', value: 80, unit: '%', color: 'red' },
      { icon: 'ghost', value: 15, unit: '%', color: 'green' },
      { icon: 'cubes', value: 10, unit: '%', color: 'green' },
    ],
    solAmount: 3.4,
    isFinalStretch: true,
  },
  {
    id: 'final-3',
    name: 'Snek',
    subtitle: 'Hiss Hiss',
    imageUrl: 'https://picsum.photos/seed/203/100/100',
    creatorAddress: 'SNEK...pump',
    age: '2m',
    marketCap: 120000,
    volume: 8000,
    fValue: 0.06,
    txCount: 50,
    stats: { users: 60, candlesticks: 10, trophies: 1, crowns: '1/2' },
    tags: [
      { icon: 'user', value: 80, unit: '%', color: 'red' },
      { icon: 'chef', value: 15, unit: '%', color: 'green', duration: '5m' },
      { icon: 'target', value: 85, unit: '%', color: 'red' },
      { icon: 'ghost', value: 5, unit: '%', color: 'green' },
      { icon: 'cubes', value: 8, unit: '%', color: 'green' },
    ],
    solAmount: 1.5,
    isFinalStretch: true,
  },
  {
    id: 'final-4',
    name: 'Mog',
    subtitle: 'Mogged',
    imageUrl: 'https://picsum.photos/seed/204/100/100',
    creatorAddress: 'MOG...pump',
    age: '3m',
    marketCap: 200000,
    volume: 15000,
    fValue: 0.08,
    txCount: 80,
    stats: { users: 100, candlesticks: 15, trophies: 2, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 85, unit: '%', color: 'red' },
      { icon: 'chef', value: 20, unit: '%', color: 'green', duration: '8m' },
      { icon: 'target', value: 90, unit: '%', color: 'red' },
      { icon: 'ghost', value: 10, unit: '%', color: 'green' },
      { icon: 'cubes', value: 12, unit: '%', color: 'green' },
    ],
    solAmount: 2.5,
    isFinalStretch: true,
  },
  {
    id: 'final-5',
    name: 'Troll',
    subtitle: 'U Mad Bro?',
    imageUrl: 'https://picsum.photos/seed/205/100/100',
    creatorAddress: 'TROL...pump',
    age: '4m',
    marketCap: 75000,
    volume: 5000,
    fValue: 0.04,
    txCount: 40,
    stats: { users: 50, candlesticks: 8, trophies: 0, crowns: '0/3' },
    tags: [
      { icon: 'user', value: 95, unit: '%', color: 'red' },
      { icon: 'chef', value: 5, unit: '%', color: 'green', duration: '3m' },
      { icon: 'target', value: 98, unit: '%', color: 'red' },
      { icon: 'ghost', value: 2, unit: '%', color: 'green' },
      { icon: 'cubes', value: 3, unit: '%', color: 'green' },
    ],
    solAmount: 0.8,
    isFinalStretch: true,
  },
  {
    id: 'final-6',
    name: 'Ricardo',
    subtitle: 'Milos',
    imageUrl: 'https://picsum.photos/seed/206/100/100',
    creatorAddress: 'RCRD...pump',
    age: '6m',
    marketCap: 300000,
    volume: 20000,
    fValue: 0.1,
    txCount: 110,
    stats: { users: 180, candlesticks: 20, trophies: 4, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 70, unit: '%', color: 'red' },
      { icon: 'chef', value: 30, unit: '%', color: 'green', duration: '12m' },
      { icon: 'target', value: 75, unit: '%', color: 'red' },
      { icon: 'ghost', value: 20, unit: '%', color: 'green' },
      { icon: 'cubes', value: 15, unit: '%', color: 'green' },
    ],
    solAmount: 4.0,
    isFinalStretch: true,
  },
  {
    id: 'final-7',
    name: 'Ugandan Knuckles',
    subtitle: 'Do U Kno De Wae',
    imageUrl: 'https://picsum.photos/seed/207/100/100',
    creatorAddress: 'WAE...pump',
    age: '7m',
    marketCap: 150000,
    volume: 10000,
    fValue: 0.07,
    txCount: 70,
    stats: { users: 90, candlesticks: 12, trophies: 1, crowns: '1/2' },
    tags: [
      { icon: 'user', value: 88, unit: '%', color: 'red' },
      { icon: 'chef', value: 12, unit: '%', color: 'green', duration: '6m' },
      { icon: 'target', value: 92, unit: '%', color: 'red' },
      { icon: 'ghost', value: 8, unit: '%', color: 'green' },
      { icon: 'cubes', value: 10, unit: '%', color: 'green' },
    ],
    solAmount: 2.0,
    isFinalStretch: true,
  },
  {
    id: 'final-8',
    name: 'Harambe',
    subtitle: 'Gone Too Soon',
    imageUrl: 'https://picsum.photos/seed/208/100/100',
    creatorAddress: 'HRMB...pump',
    age: '8m',
    marketCap: 400000,
    volume: 30000,
    fValue: 0.11,
    txCount: 150,
    stats: { users: 250, candlesticks: 25, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 65, unit: '%', color: 'red' },
      { icon: 'chef', value: 35, unit: '%', color: 'green', duration: '15m' },
      { icon: 'target', value: 70, unit: '%', color: 'red' },
      { icon: 'ghost', value: 25, unit: '%', color: 'green' },
      { icon: 'cubes', value: 20, unit: '%', color: 'green' },
    ],
    solAmount: 5.0,
    isFinalStretch: true,
  },
  {
    id: 'final-9',
    name: 'Dat Boi',
    subtitle: 'O Shit Waddup',
    imageUrl: 'https://picsum.photos/seed/209/100/100',
    creatorAddress: 'BOI...pump',
    age: '9m',
    marketCap: 180000,
    volume: 12000,
    fValue: 0.08,
    txCount: 90,
    stats: { users: 110, candlesticks: 14, trophies: 2, crowns: '1/2' },
    tags: [
      { icon: 'user', value: 82, unit: '%', color: 'red' },
      { icon: 'chef', value: 18, unit: '%', color: 'green', duration: '7m' },
      { icon: 'target', value: 88, unit: '%', color: 'red' },
      { icon: 'ghost', value: 12, unit: '%', color: 'green' },
      { icon: 'cubes', value: 14, unit: '%', color: 'green' },
    ],
    solAmount: 2.2,
    isFinalStretch: true,
  },
  {
    id: 'final-10',
    name: 'Grumpy Cat',
    subtitle: 'NO',
    imageUrl: 'https://picsum.photos/seed/210/100/100',
    creatorAddress: 'GRMP...pump',
    age: '10m',
    marketCap: 250000,
    volume: 18000,
    fValue: 0.09,
    txCount: 100,
    stats: { users: 160, candlesticks: 18, trophies: 3, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 78, unit: '%', color: 'red' },
      { icon: 'chef', value: 22, unit: '%', color: 'green', duration: '9m' },
      { icon: 'target', value: 85, unit: '%', color: 'red' },
      { icon: 'ghost', value: 15, unit: '%', color: 'green' },
      { icon: 'cubes', value: 18, unit: '%', color: 'green' },
    ],
    solAmount: 3.0,
    isFinalStretch: true,
  },
  {
    id: 'final-11',
    name: 'Nyan Cat',
    subtitle: 'Rainbow Pop-Tart',
    imageUrl: 'https://picsum.photos/seed/211/100/100',
    creatorAddress: 'NYAN...pump',
    age: '11m',
    marketCap: 600000,
    volume: 40000,
    fValue: 0.15,
    txCount: 200,
    stats: { users: 300, candlesticks: 30, trophies: 6, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 60, unit: '%', color: 'red' },
      { icon: 'chef', value: 40, unit: '%', color: 'green', duration: '20m' },
      { icon: 'target', value: 65, unit: '%', color: 'red' },
      { icon: 'ghost', value: 30, unit: '%', color: 'green' },
      { icon: 'cubes', value: 25, unit: '%', color: 'green' },
    ],
    solAmount: 8.0,
    isFinalStretch: true,
  },
  {
    id: 'final-12',
    name: 'Keyboard Cat',
    subtitle: 'Play Him Off',
    imageUrl: 'https://picsum.photos/seed/212/100/100',
    creatorAddress: 'KBRD...pump',
    age: '12m',
    marketCap: 220000,
    volume: 16000,
    fValue: 0.085,
    txCount: 95,
    stats: { users: 140, candlesticks: 16, trophies: 2, crowns: '1/2' },
    tags: [
      { icon: 'user', value: 80, unit: '%', color: 'red' },
      { icon: 'chef', value: 20, unit: '%', color: 'green', duration: '10m' },
      { icon: 'target', value: 87, unit: '%', color: 'red' },
      { icon: 'ghost', value: 14, unit: '%', color: 'green' },
      { icon: 'cubes', value: 16, unit: '%', color: 'green' },
    ],
    solAmount: 2.8,
    isFinalStretch: true,
  },
  {
    id: 'final-13',
    name: 'Doge',
    subtitle: 'Wow',
    imageUrl: 'https://picsum.photos/seed/213/100/100',
    creatorAddress: 'WOW...pump',
    age: '13m',
    marketCap: 1000000,
    volume: 80000,
    fValue: 0.2,
    txCount: 300,
    stats: { users: 500, candlesticks: 40, trophies: 8, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 50, unit: '%', color: 'red' },
      { icon: 'chef', value: 50, unit: '%', color: 'green', duration: '30m' },
      { icon: 'target', value: 55, unit: '%', color: 'red' },
      { icon: 'ghost', value: 40, unit: '%', color: 'green' },
      { icon: 'cubes', value: 30, unit: '%', color: 'green' },
    ],
    solAmount: 15.0,
    isFinalStretch: true,
  },
  {
    id: 'final-14',
    name: 'Longcat',
    subtitle: 'Is Long',
    imageUrl: 'https://picsum.photos/seed/214/100/100',
    creatorAddress: 'LONG...pump',
    age: '14m',
    marketCap: 90000,
    volume: 7000,
    fValue: 0.05,
    txCount: 60,
    stats: { users: 70, candlesticks: 9, trophies: 1, crowns: '1/3' },
    tags: [
      { icon: 'user', value: 90, unit: '%', color: 'red' },
      { icon: 'chef', value: 10, unit: '%', color: 'green', duration: '4m' },
      { icon: 'target', value: 94, unit: '%', color: 'red' },
      { icon: 'ghost', value: 7, unit: '%', color: 'green' },
      { icon: 'cubes', value: 9, unit: '%', color: 'green' },
    ],
    solAmount: 1.2,
    isFinalStretch: true,
  },
  {
    id: 'final-15',
    name: 'Tacgnol',
    subtitle: 'Is Also Long',
    imageUrl: 'https://picsum.photos/seed/215/100/100',
    creatorAddress: 'TACG...pump',
    age: '15m',
    marketCap: 85000,
    volume: 6500,
    fValue: 0.045,
    txCount: 55,
    stats: { users: 65, candlesticks: 8, trophies: 1, crowns: '1/3' },
    tags: [
      { icon: 'user', value: 91, unit: '%', color: 'red' },
      { icon: 'chef', value: 9, unit: '%', color: 'green', duration: '3.5m' },
      { icon: 'target', value: 95, unit: '%', color: 'red' },
      { icon: 'ghost', value: 6, unit: '%', color: 'green' },
      { icon: 'cubes', value: 8, unit: '%', color: 'green' },
    ],
    solAmount: 1.1,
    isFinalStretch: true,
  },
  {
    id: 'final-16',
    name: 'Pepe Silvia',
    subtitle: 'There Is No Pepe Silvia',
    imageUrl: 'https://picsum.photos/seed/216/100/100',
    creatorAddress: 'SLVA...pump',
    age: '16m',
    marketCap: 65000,
    volume: 4500,
    fValue: 0.03,
    txCount: 35,
    stats: { users: 45, candlesticks: 7, trophies: 0, crowns: '0/4' },
    tags: [
      { icon: 'user', value: 96, unit: '%', color: 'red' },
      { icon: 'chef', value: 4, unit: '%', color: 'green', duration: '2m' },
      { icon: 'target', value: 99, unit: '%', color: 'red' },
      { icon: 'ghost', value: 1, unit: '%', color: 'green' },
      { icon: 'cubes', value: 2, unit: '%', color: 'green' },
    ],
    solAmount: 0.7,
    isFinalStretch: true,
  },
  {
    id: 'final-17',
    name: 'Giga Brain',
    subtitle: 'Ascended',
    imageUrl: 'https://picsum.photos/seed/217/100/100',
    creatorAddress: 'GIGA...pump',
    age: '18m',
    marketCap: 750000,
    volume: 50000,
    fValue: 0.18,
    txCount: 250,
    stats: { users: 400, candlesticks: 35, trophies: 7, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 55, unit: '%', color: 'red' },
      { icon: 'chef', value: 45, unit: '%', color: 'green', duration: '25m' },
      { icon: 'target', value: 60, unit: '%', color: 'red' },
      { icon: 'ghost', value: 35, unit: '%', color: 'green' },
      { icon: 'cubes', value: 28, unit: '%', color: 'green' },
    ],
    solAmount: 12.0,
    isFinalStretch: true,
  },
  {
    id: 'final-18',
    name: 'This is Fine',
    subtitle: 'Everything is Fine',
    imageUrl: 'https://picsum.photos/seed/218/100/100',
    creatorAddress: 'FINE...pump',
    age: '20m',
    marketCap: 50000,
    volume: 3000,
    fValue: 0.02,
    txCount: 25,
    stats: { users: 30, candlesticks: 5, trophies: 0, crowns: '0/5' },
    tags: [
      { icon: 'user', value: 98, unit: '%', color: 'red' },
      { icon: 'chef', value: 2, unit: '%', color: 'green', duration: '1m' },
      { icon: 'target', value: 100, unit: '%', color: 'red' },
      { icon: 'ghost', value: 0, unit: '%', color: 'green' },
      { icon: 'cubes', value: 1, unit: '%', color: 'green' },
    ],
    solAmount: 0.4,
    isFinalStretch: true,
  },
  {
    id: 'final-19',
    name: 'Sanic',
    subtitle: 'Gotta Go Fast',
    imageUrl: 'https://picsum.photos/seed/219/100/100',
    creatorAddress: 'SNIC...pump',
    age: '22m',
    marketCap: 130000,
    volume: 9000,
    fValue: 0.065,
    txCount: 85,
    stats: { users: 105, candlesticks: 13, trophies: 2, crowns: '1/2' },
    tags: [
      { icon: 'user', value: 83, unit: '%', color: 'red' },
      { icon: 'chef', value: 17, unit: '%', color: 'green', duration: '6.5m' },
      { icon: 'target', value: 89, unit: '%', color: 'red' },
      { icon: 'ghost', value: 11, unit: '%', color: 'green' },
      { icon: 'cubes', value: 13, unit: '%', color: 'green' },
    ],
    solAmount: 1.8,
    isFinalStretch: true,
  },
  {
    id: 'final-20',
    name: 'Dolan',
    subtitle: 'Gooby Pls',
    imageUrl: 'https://picsum.photos/seed/220/100/100',
    creatorAddress: 'DLAN...pump',
    age: '25m',
    marketCap: 40000,
    volume: 2500,
    fValue: 0.015,
    txCount: 20,
    stats: { users: 25, candlesticks: 4, trophies: 0, crowns: '0/6' },
    tags: [
      { icon: 'user', value: 97, unit: '%', color: 'red' },
      { icon: 'chef', value: 3, unit: '%', color: 'green', duration: '1.5m' },
      { icon: 'target', value: 99, unit: '%', color: 'red' },
      { icon: 'ghost', value: 1, unit: '%', color: 'green' },
      { icon: 'cubes', value: 2, unit: '%', color: 'green' },
    ],
    solAmount: 0.3,
    isFinalStretch: true,
  },

  // Migrated
  {
    id: 'wif-1',
    name: 'WIF',
    subtitle: 'dog wif hat',
    imageUrl: 'https://picsum.photos/seed/5/100/100',
    creatorAddress: 'Emn5...aRTy',
    age: '30m',
    marketCap: 1200000,
    volume: 80000,
    fValue: 0.25,
    txCount: 250,
    stats: { users: 500, candlesticks: 10, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 60, unit: '%', color: 'green' },
      { icon: 'chef', value: 40, unit: '%', color: 'green', duration: '30m' },
      { icon: 'target', value: 70, unit: '%', color: 'green' },
      { icon: 'ghost', value: 20, unit: '%', color: 'green' },
      { icon: 'cubes', value: 20, unit: '%', color: 'green' },
    ],
    solAmount: 10.1,
    isMigrated: true,
  },
  {
    id: 'migrated-2',
    name: 'Popcat',
    subtitle: 'Click',
    imageUrl: 'https://picsum.photos/seed/302/100/100',
    creatorAddress: 'POPC...pump',
    age: '35m',
    marketCap: 800000,
    volume: 60000,
    fValue: 0.2,
    txCount: 200,
    stats: { users: 400, candlesticks: 8, trophies: 4, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 65, unit: '%', color: 'green' },
      { icon: 'chef', value: 35, unit: '%', color: 'green', duration: '25m' },
      { icon: 'target', value: 75, unit: '%', color: 'green' },
      { icon: 'ghost', value: 22, unit: '%', color: 'green' },
      { icon: 'cubes', value: 25, unit: '%', color: 'green' },
    ],
    solAmount: 12.5,
    isMigrated: true,
  },
  {
    id: 'migrated-3',
    name: 'Peepo',
    subtitle: 'Happy',
    imageUrl: 'https://picsum.photos/seed/303/100/100',
    creatorAddress: 'PEPO...pump',
    age: '40m',
    marketCap: 1500000,
    volume: 100000,
    fValue: 0.3,
    txCount: 300,
    stats: { users: 600, candlesticks: 12, trophies: 6, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 70, unit: '%', color: 'green' },
      { icon: 'chef', value: 30, unit: '%', color: 'green', duration: '35m' },
      { icon: 'target', value: 80, unit: '%', color: 'green' },
      { icon: 'ghost', value: 25, unit: '%', color: 'green' },
      { icon: 'cubes', value: 30, unit: '%', color: 'green' },
    ],
    solAmount: 20.0,
    isMigrated: true,
  },
  {
    id: 'migrated-4',
    name: 'Drake',
    subtitle: 'Hotline Bling',
    imageUrl: 'https://picsum.photos/seed/304/100/100',
    creatorAddress: 'DRKE...pump',
    age: '45m',
    marketCap: 900000,
    volume: 70000,
    fValue: 0.22,
    txCount: 220,
    stats: { users: 450, candlesticks: 9, trophies: 4, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 68, unit: '%', color: 'green' },
      { icon: 'chef', value: 32, unit: '%', color: 'green', duration: '28m' },
      { icon: 'target', value: 78, unit: '%', color: 'green' },
      { icon: 'ghost', value: 24, unit: '%', color: 'green' },
      { icon: 'cubes', value: 28, unit: '%', color: 'green' },
    ],
    solAmount: 15.5,
    isMigrated: true,
  },
  {
    id: 'migrated-5',
    name: 'Feels Guy',
    subtitle: 'I Know That Feel Bro',
    imageUrl: 'https://picsum.photos/seed/305/100/100',
    creatorAddress: 'FEEL...pump',
    age: '50m',
    marketCap: 700000,
    volume: 55000,
    fValue: 0.18,
    txCount: 180,
    stats: { users: 350, candlesticks: 7, trophies: 3, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 62, unit: '%', color: 'green' },
      { icon: 'chef', value: 38, unit: '%', color: 'green', duration: '22m' },
      { icon: 'target', value: 72, unit: '%', color: 'green' },
      { icon: 'ghost', value: 20, unit: '%', color: 'green' },
      { icon: 'cubes', value: 22, unit: '%', color: 'green' },
    ],
    solAmount: 11.0,
    isMigrated: true,
  },
  {
    id: 'migrated-6',
    name: 'Hide the Pain Harold',
    subtitle: 'Smile Through the Pain',
    imageUrl: 'https://picsum.photos/seed/306/100/100',
    creatorAddress: 'HRLD...pump',
    age: '55m',
    marketCap: 1100000,
    volume: 90000,
    fValue: 0.28,
    txCount: 280,
    stats: { users: 550, candlesticks: 11, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 69, unit: '%', color: 'green' },
      { icon: 'chef', value: 31, unit: '%', color: 'green', duration: '32m' },
      { icon: 'target', value: 79, unit: '%', color: 'green' },
      { icon: 'ghost', value: 26, unit: '%', color: 'green' },
      { icon: 'cubes', value: 29, unit: '%', color: 'green' },
    ],
    solAmount: 18.0,
    isMigrated: true,
  },
  {
    id: 'migrated-7',
    name: 'Distracted Boyfriend',
    subtitle: 'Looking Back',
    imageUrl: 'https://picsum.photos/seed/307/100/100',
    creatorAddress: 'LOOK...pump',
    age: '1h',
    marketCap: 950000,
    volume: 75000,
    fValue: 0.24,
    txCount: 240,
    stats: { users: 480, candlesticks: 10, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 67, unit: '%', color: 'green' },
      { icon: 'chef', value: 33, unit: '%', color: 'green', duration: '30m' },
      { icon: 'target', value: 77, unit: '%', color: 'green' },
      { icon: 'ghost', value: 23, unit: '%', color: 'green' },
      { icon: 'cubes', value: 27, unit: '%', color: 'green' },
    ],
    solAmount: 16.0,
    isMigrated: true,
  },
  {
    id: 'migrated-8',
    name: 'Woman Yelling at a Cat',
    subtitle: 'Smudge the Cat',
    imageUrl: 'https://picsum.photos/seed/308/100/100',
    creatorAddress: 'SMDG...pump',
    age: '1.1h',
    marketCap: 1300000,
    volume: 95000,
    fValue: 0.29,
    txCount: 290,
    stats: { users: 580, candlesticks: 13, trophies: 6, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 71, unit: '%', color: 'green' },
      { icon: 'chef', value: 29, unit: '%', color: 'green', duration: '38m' },
      { icon: 'target', value: 81, unit: '%', color: 'green' },
      { icon: 'ghost', value: 27, unit: '%', color: 'green' },
      { icon: 'cubes', value: 31, unit: '%', color: 'green' },
    ],
    solAmount: 22.0,
    isMigrated: true,
  },
  {
    id: 'migrated-9',
    name: 'Is This a Pigeon?',
    subtitle: 'Butterfly Meme',
    imageUrl: 'https://picsum.photos/seed/309/100/100',
    creatorAddress: 'PIGN...pump',
    age: '1.2h',
    marketCap: 850000,
    volume: 65000,
    fValue: 0.21,
    txCount: 210,
    stats: { users: 420, candlesticks: 9, trophies: 4, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 66, unit: '%', color: 'green' },
      { icon: 'chef', value: 34, unit: '%', color: 'green', duration: '27m' },
      { icon: 'target', value: 76, unit: '%', color: 'green' },
      { icon: 'ghost', value: 21, unit: '%', color: 'green' },
      { icon: 'cubes', value: 26, unit: '%', color: 'green' },
    ],
    solAmount: 14.0,
    isMigrated: true,
  },
  {
    id: 'migrated-10',
    name: 'Expanding Brain',
    subtitle: 'Galaxy Brain',
    imageUrl: 'https://picsum.photos/seed/310/100/100',
    creatorAddress: 'EXPD...pump',
    age: '1.3h',
    marketCap: 1600000,
    volume: 110000,
    fValue: 0.32,
    txCount: 320,
    stats: { users: 650, candlesticks: 14, trophies: 7, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 72, unit: '%', color: 'green' },
      { icon: 'chef', value: 28, unit: '%', color: 'green', duration: '40m' },
      { icon: 'target', value: 82, unit: '%', color: 'green' },
      { icon: 'ghost', value: 28, unit: '%', color: 'green' },
      { icon: 'cubes', value: 33, unit: '%', color: 'green' },
    ],
    solAmount: 25.0,
    isMigrated: true,
  },
  {
    id: 'migrated-11',
    name: 'Roll Safe',
    subtitle: 'Think About It',
    imageUrl: 'https://picsum.photos/seed/311/100/100',
    creatorAddress: 'SAFE...pump',
    age: '1.4h',
    marketCap: 1000000,
    volume: 85000,
    fValue: 0.26,
    txCount: 260,
    stats: { users: 520, candlesticks: 11, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 68, unit: '%', color: 'green' },
      { icon: 'chef', value: 32, unit: '%', color: 'green', duration: '33m' },
      { icon: 'target', value: 78, unit: '%', color: 'green' },
      { icon: 'ghost', value: 25, unit: '%', color: 'green' },
      { icon: 'cubes', value: 28, unit: '%', color: 'green' },
    ],
    solAmount: 17.0,
    isMigrated: true,
  },
  {
    id: 'migrated-12',
    name: 'Surprised Pikachu',
    subtitle: 'Gasp',
    imageUrl: 'https://picsum.photos/seed/312/100/100',
    creatorAddress: 'PIKA...pump',
    age: '1.5h',
    marketCap: 1400000,
    volume: 100000,
    fValue: 0.31,
    txCount: 310,
    stats: { users: 620, candlesticks: 13, trophies: 6, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 70, unit: '%', color: 'green' },
      { icon: 'chef', value: 30, unit: '%', color: 'green', duration: '36m' },
      { icon: 'target', value: 80, unit: '%', color: 'green' },
      { icon: 'ghost', value: 27, unit: '%', color: 'green' },
      { icon: 'cubes', value: 32, unit: '%', color: 'green' },
    ],
    solAmount: 23.0,
    isMigrated: true,
  },
  {
    id: 'migrated-13',
    name: 'Arthur\'s Fist',
    subtitle: 'When you\'re angry',
    imageUrl: 'https://picsum.photos/seed/313/100/100',
    creatorAddress: 'FIST...pump',
    age: '1.6h',
    marketCap: 750000,
    volume: 60000,
    fValue: 0.19,
    txCount: 190,
    stats: { users: 380, candlesticks: 8, trophies: 4, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 64, unit: '%', color: 'green' },
      { icon: 'chef', value: 36, unit: '%', color: 'green', duration: '24m' },
      { icon: 'target', value: 74, unit: '%', color: 'green' },
      { icon: 'ghost', value: 20, unit: '%', color: 'green' },
      { icon: 'cubes', value: 24, unit: '%', color: 'green' },
    ],
    solAmount: 11.5,
    isMigrated: true,
  },
  {
    id: 'migrated-14',
    name: 'Kermit Sipping Tea',
    subtitle: 'But That\'s None of My Business',
    imageUrl: 'https://picsum.photos/seed/314/100/100',
    creatorAddress: 'KERM...pump',
    age: '1.7h',
    marketCap: 1250000,
    volume: 92000,
    fValue: 0.28,
    txCount: 285,
    stats: { users: 570, candlesticks: 12, trophies: 6, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 69, unit: '%', color: 'green' },
      { icon: 'chef', value: 31, unit: '%', color: 'green', duration: '34m' },
      { icon: 'target', value: 79, unit: '%', color: 'green' },
      { icon: 'ghost', value: 26, unit: '%', color: 'green' },
      { icon: 'cubes', value: 30, unit: '%', color: 'green' },
    ],
    solAmount: 21.0,
    isMigrated: true,
  },
  {
    id: 'migrated-15',
    name: 'Gru\'s Plan',
    subtitle: 'The Four Panels',
    imageUrl: 'https://picsum.photos/seed/315/100/100',
    creatorAddress: 'GRU...pump',
    age: '1.8h',
    marketCap: 880000,
    volume: 68000,
    fValue: 0.22,
    txCount: 225,
    stats: { users: 440, candlesticks: 10, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 67, unit: '%', color: 'green' },
      { icon: 'chef', value: 33, unit: '%', color: 'green', duration: '29m' },
      { icon: 'target', value: 77, unit: '%', color: 'green' },
      { icon: 'ghost', value: 22, unit: '%', color: 'green' },
      { icon: 'cubes', value: 27, unit: '%', color: 'green' },
    ],
    solAmount: 14.5,
    isMigrated: true,
  },
  {
    id: 'migrated-16',
    name: 'Change My Mind',
    subtitle: 'Steven Crowder',
    imageUrl: 'https://picsum.photos/seed/316/100/100',
    creatorAddress: 'MIND...pump',
    age: '1.9h',
    marketCap: 1050000,
    volume: 88000,
    fValue: 0.27,
    txCount: 270,
    stats: { users: 530, candlesticks: 11, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 68, unit: '%', color: 'green' },
      { icon: 'chef', value: 32, unit: '%', color: 'green', duration: '31m' },
      { icon: 'target', value: 78, unit: '%', color: 'green' },
      { icon: 'ghost', value: 25, unit: '%', color: 'green' },
      { icon: 'cubes', value: 29, unit: '%', color: 'green' },
    ],
    solAmount: 17.5,
    isMigrated: true,
  },
  {
    id: 'migrated-17',
    name: 'Two Buttons',
    subtitle: 'The Choice',
    imageUrl: 'https://picsum.photos/seed/317/100/100',
    creatorAddress: 'BTNS...pump',
    age: '2h',
    marketCap: 800000,
    volume: 62000,
    fValue: 0.2,
    txCount: 205,
    stats: { users: 410, candlesticks: 9, trophies: 4, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 65, unit: '%', color: 'green' },
      { icon: 'chef', value: 35, unit: '%', color: 'green', duration: '26m' },
      { icon: 'target', value: 75, unit: '%', color: 'green' },
      { icon: 'ghost', value: 21, unit: '%', color: 'green' },
      { icon: 'cubes', value: 25, unit: '%', color: 'green' },
    ],
    solAmount: 13.0,
    isMigrated: true,
  },
  {
    id: 'migrated-18',
    name: 'Boardroom Suggestion',
    subtitle: 'Thrown Out the Window',
    imageUrl: 'https://picsum.photos/seed/318/100/100',
    creatorAddress: 'BRDM...pump',
    age: '2.1h',
    marketCap: 920000,
    volume: 72000,
    fValue: 0.23,
    txCount: 230,
    stats: { users: 460, candlesticks: 10, trophies: 5, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 67, unit: '%', color: 'green' },
      { icon: 'chef', value: 33, unit: '%', color: 'green', duration: '30m' },
      { icon: 'target', value: 77, unit: '%', color: 'green' },
      { icon: 'ghost', value: 23, unit: '%', color: 'green' },
      { icon: 'cubes', value: 28, unit: '%', color: 'green' },
    ],
    solAmount: 15.0,
    isMigrated: true,
  },
  {
    id: 'migrated-19',
    name: 'The Scroll of Truth',
    subtitle: 'NYEH!',
    imageUrl: 'https://picsum.photos/seed/319/100/100',
    creatorAddress: 'TRTH...pump',
    age: '2.2h',
    marketCap: 1150000,
    volume: 91000,
    fValue: 0.28,
    txCount: 280,
    stats: { users: 560, candlesticks: 12, trophies: 6, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 69, unit: '%', color: 'green' },
      { icon: 'chef', value: 31, unit: '%', color: 'green', duration: '35m' },
      { icon: 'target', value: 79, unit: '%', color: 'green' },
      { icon: 'ghost', value: 26, unit: '%', color: 'green' },
      { icon: 'cubes', value: 31, unit: '%', color: 'green' },
    ],
    solAmount: 19.0,
    isMigrated: true,
  },
  {
    id: 'migrated-20',
    name: 'Spongebob',
    subtitle: 'Ight Imma Head Out',
    imageUrl: 'https://picsum.photos/seed/320/100/100',
    creatorAddress: 'IGHT...pump',
    age: '2.3h',
    marketCap: 1800000,
    volume: 120000,
    fValue: 0.35,
    txCount: 350,
    stats: { users: 700, candlesticks: 15, trophies: 8, crowns: '1/1' },
    tags: [
      { icon: 'user', value: 75, unit: '%', color: 'green' },
      { icon: 'chef', value: 25, unit: '%', color: 'green', duration: '45m' },
      { icon: 'target', value: 85, unit: '%', color: 'green' },
      { icon: 'ghost', value: 30, unit: '%', color: 'green' },
      { icon: 'cubes', value: 35, unit: '%', color: 'green' },
    ],
    solAmount: 30.0,
    isMigrated: true,
  },
];

export const getInitialTokens = (): Token[] => {
  // Deep copy to prevent mutation of the original data
  const copiedTokens: Token[] = JSON.parse(JSON.stringify(tokens));

  // Assign random similar tokens
  return copiedTokens.map(token => {
    const similarTokensCount = Math.floor(Math.random() * 3); // 0, 1, or 2
    const shuffled = allTokensForSimilarity.sort(() => 0.5 - Math.random());
    token.similarTokens = shuffled.slice(0, similarTokensCount);
    return token;
  });
};
